# try:  ,  except is used to save our program, if any error occur these save our program and our program works smoothly
# suppose if we give inout an integer in case of string it will manage and will give an output with exception handling

# n1=int(input("enter first number\n"))
# n2=int(input("enter second number\n"))
# print("the sum is=", n1 + n2)

# here if we give an integer as input it will run smoothly but give an string then will through an error


# here it will also work for integer , but will give an error for string
# n1=input("enter first number\n")
# n2=input("enter second number\n")
# print("the sum is=", int(n1) + int(n2))


# here n1 is accepting a string and n2 is accepting an integer, but it will not through an error ,
# it will print this string as base of 10
# n1=input("enter first number\n")
# n2=int(input("enter second number\n"))
# try:
#     print("the sum is=", int(n1) + n2)
# except Exception as n1 :    #here we are handling n1(string) as exception
#     print(n1)
# print("this line is important to print\n")

